//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_Soap.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: A geração do contrato de mensagem a partir do nome de elemento GetPecaMaiorPrejuizoResult a partir do espaço de nomes http://tempuri.org/ não está marcada como anulável
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPecaMaiorPrejuizo", ReplyAction="*")]
        Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoResponse GetPecaMaiorPrejuizo(Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPecaMaiorPrejuizo", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoResponse> GetPecaMaiorPrejuizoAsync(Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterCustosTotaisPorPeriodo", ReplyAction="*")]
        decimal ObterCustosTotaisPorPeriodo(System.DateTime inicio, System.DateTime fim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterCustosTotaisPorPeriodo", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> ObterCustosTotaisPorPeriodoAsync(System.DateTime inicio, System.DateTime fim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterLucroTotalPorPeriodo", ReplyAction="*")]
        decimal ObterLucroTotalPorPeriodo(System.DateTime inicio, System.DateTime fim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterLucroTotalPorPeriodo", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> ObterLucroTotalPorPeriodoAsync(System.DateTime inicio, System.DateTime fim);
        
        // CODEGEN: A geração do contrato de mensagem a partir do nome de elemento ObterPrejuizoTotalPorPecaResult a partir do espaço de nomes http://tempuri.org/ não está marcada como anulável
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterPrejuizoTotalPorPeca", ReplyAction="*")]
        Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaResponse ObterPrejuizoTotalPorPeca(Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterPrejuizoTotalPorPeca", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaResponse> ObterPrejuizoTotalPorPecaAsync(Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaRequest request);
        
        // CODEGEN: A geração do contrato de mensagem a partir do nome de elemento codigoPeca a partir do espaço de nomes http://tempuri.org/ não está marcada como anulável
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterDadosFinanceirosPorPeca", ReplyAction="*")]
        Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaResponse ObterDadosFinanceirosPorPeca(Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterDadosFinanceirosPorPeca", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaResponse> ObterDadosFinanceirosPorPecaAsync(Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPecaMaiorPrejuizoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPecaMaiorPrejuizo", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoRequestBody Body;
        
        public GetPecaMaiorPrejuizoRequest() {
        }
        
        public GetPecaMaiorPrejuizoRequest(Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPecaMaiorPrejuizoRequestBody {
        
        public GetPecaMaiorPrejuizoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPecaMaiorPrejuizoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPecaMaiorPrejuizoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoResponseBody Body;
        
        public GetPecaMaiorPrejuizoResponse() {
        }
        
        public GetPecaMaiorPrejuizoResponse(Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPecaMaiorPrejuizoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPecaMaiorPrejuizoResult;
        
        public GetPecaMaiorPrejuizoResponseBody() {
        }
        
        public GetPecaMaiorPrejuizoResponseBody(string GetPecaMaiorPrejuizoResult) {
            this.GetPecaMaiorPrejuizoResult = GetPecaMaiorPrejuizoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterPrejuizoTotalPorPecaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterPrejuizoTotalPorPeca", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaRequestBody Body;
        
        public ObterPrejuizoTotalPorPecaRequest() {
        }
        
        public ObterPrejuizoTotalPorPecaRequest(Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterPrejuizoTotalPorPecaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime inicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fim;
        
        public ObterPrejuizoTotalPorPecaRequestBody() {
        }
        
        public ObterPrejuizoTotalPorPecaRequestBody(System.DateTime inicio, System.DateTime fim) {
            this.inicio = inicio;
            this.fim = fim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterPrejuizoTotalPorPecaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterPrejuizoTotalPorPecaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaResponseBody Body;
        
        public ObterPrejuizoTotalPorPecaResponse() {
        }
        
        public ObterPrejuizoTotalPorPecaResponse(Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterPrejuizoTotalPorPecaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_Soap.ServiceReference1.ArrayOfString ObterPrejuizoTotalPorPecaResult;
        
        public ObterPrejuizoTotalPorPecaResponseBody() {
        }
        
        public ObterPrejuizoTotalPorPecaResponseBody(Cliente_Soap.ServiceReference1.ArrayOfString ObterPrejuizoTotalPorPecaResult) {
            this.ObterPrejuizoTotalPorPecaResult = ObterPrejuizoTotalPorPecaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterDadosFinanceirosPorPecaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterDadosFinanceirosPorPeca", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaRequestBody Body;
        
        public ObterDadosFinanceirosPorPecaRequest() {
        }
        
        public ObterDadosFinanceirosPorPecaRequest(Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterDadosFinanceirosPorPecaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigoPeca;
        
        public ObterDadosFinanceirosPorPecaRequestBody() {
        }
        
        public ObterDadosFinanceirosPorPecaRequestBody(string codigoPeca) {
            this.codigoPeca = codigoPeca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterDadosFinanceirosPorPecaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterDadosFinanceirosPorPecaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaResponseBody Body;
        
        public ObterDadosFinanceirosPorPecaResponse() {
        }
        
        public ObterDadosFinanceirosPorPecaResponse(Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterDadosFinanceirosPorPecaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObterDadosFinanceirosPorPecaResult;
        
        public ObterDadosFinanceirosPorPecaResponseBody() {
        }
        
        public ObterDadosFinanceirosPorPecaResponseBody(string ObterDadosFinanceirosPorPecaResult) {
            this.ObterDadosFinanceirosPorPecaResult = ObterDadosFinanceirosPorPecaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Cliente_Soap.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Cliente_Soap.ServiceReference1.WebService1Soap>, Cliente_Soap.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoResponse Cliente_Soap.ServiceReference1.WebService1Soap.GetPecaMaiorPrejuizo(Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoRequest request) {
            return base.Channel.GetPecaMaiorPrejuizo(request);
        }
        
        public string GetPecaMaiorPrejuizo() {
            Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoRequest inValue = new Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoRequest();
            inValue.Body = new Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoRequestBody();
            Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoResponse retVal = ((Cliente_Soap.ServiceReference1.WebService1Soap)(this)).GetPecaMaiorPrejuizo(inValue);
            return retVal.Body.GetPecaMaiorPrejuizoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoResponse> Cliente_Soap.ServiceReference1.WebService1Soap.GetPecaMaiorPrejuizoAsync(Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoRequest request) {
            return base.Channel.GetPecaMaiorPrejuizoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoResponse> GetPecaMaiorPrejuizoAsync() {
            Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoRequest inValue = new Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoRequest();
            inValue.Body = new Cliente_Soap.ServiceReference1.GetPecaMaiorPrejuizoRequestBody();
            return ((Cliente_Soap.ServiceReference1.WebService1Soap)(this)).GetPecaMaiorPrejuizoAsync(inValue);
        }
        
        public decimal ObterCustosTotaisPorPeriodo(System.DateTime inicio, System.DateTime fim) {
            return base.Channel.ObterCustosTotaisPorPeriodo(inicio, fim);
        }
        
        public System.Threading.Tasks.Task<decimal> ObterCustosTotaisPorPeriodoAsync(System.DateTime inicio, System.DateTime fim) {
            return base.Channel.ObterCustosTotaisPorPeriodoAsync(inicio, fim);
        }
        
        public decimal ObterLucroTotalPorPeriodo(System.DateTime inicio, System.DateTime fim) {
            return base.Channel.ObterLucroTotalPorPeriodo(inicio, fim);
        }
        
        public System.Threading.Tasks.Task<decimal> ObterLucroTotalPorPeriodoAsync(System.DateTime inicio, System.DateTime fim) {
            return base.Channel.ObterLucroTotalPorPeriodoAsync(inicio, fim);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaResponse Cliente_Soap.ServiceReference1.WebService1Soap.ObterPrejuizoTotalPorPeca(Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaRequest request) {
            return base.Channel.ObterPrejuizoTotalPorPeca(request);
        }
        
        public Cliente_Soap.ServiceReference1.ArrayOfString ObterPrejuizoTotalPorPeca(System.DateTime inicio, System.DateTime fim) {
            Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaRequest inValue = new Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaRequest();
            inValue.Body = new Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaRequestBody();
            inValue.Body.inicio = inicio;
            inValue.Body.fim = fim;
            Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaResponse retVal = ((Cliente_Soap.ServiceReference1.WebService1Soap)(this)).ObterPrejuizoTotalPorPeca(inValue);
            return retVal.Body.ObterPrejuizoTotalPorPecaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaResponse> Cliente_Soap.ServiceReference1.WebService1Soap.ObterPrejuizoTotalPorPecaAsync(Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaRequest request) {
            return base.Channel.ObterPrejuizoTotalPorPecaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaResponse> ObterPrejuizoTotalPorPecaAsync(System.DateTime inicio, System.DateTime fim) {
            Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaRequest inValue = new Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaRequest();
            inValue.Body = new Cliente_Soap.ServiceReference1.ObterPrejuizoTotalPorPecaRequestBody();
            inValue.Body.inicio = inicio;
            inValue.Body.fim = fim;
            return ((Cliente_Soap.ServiceReference1.WebService1Soap)(this)).ObterPrejuizoTotalPorPecaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaResponse Cliente_Soap.ServiceReference1.WebService1Soap.ObterDadosFinanceirosPorPeca(Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaRequest request) {
            return base.Channel.ObterDadosFinanceirosPorPeca(request);
        }
        
        public string ObterDadosFinanceirosPorPeca(string codigoPeca) {
            Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaRequest inValue = new Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaRequest();
            inValue.Body = new Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaRequestBody();
            inValue.Body.codigoPeca = codigoPeca;
            Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaResponse retVal = ((Cliente_Soap.ServiceReference1.WebService1Soap)(this)).ObterDadosFinanceirosPorPeca(inValue);
            return retVal.Body.ObterDadosFinanceirosPorPecaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaResponse> Cliente_Soap.ServiceReference1.WebService1Soap.ObterDadosFinanceirosPorPecaAsync(Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaRequest request) {
            return base.Channel.ObterDadosFinanceirosPorPecaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaResponse> ObterDadosFinanceirosPorPecaAsync(string codigoPeca) {
            Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaRequest inValue = new Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaRequest();
            inValue.Body = new Cliente_Soap.ServiceReference1.ObterDadosFinanceirosPorPecaRequestBody();
            inValue.Body.codigoPeca = codigoPeca;
            return ((Cliente_Soap.ServiceReference1.WebService1Soap)(this)).ObterDadosFinanceirosPorPecaAsync(inValue);
        }
    }
}
